### ISSUE TITLE
Documentation site alternatives

### ISSUE THREAD

**Issue by pardom** [oolong-kt/oolong#42]
Currently the project site is generated with GitBook. Let's investigate alternatives that allow more flexibility.

Alternatives:
- https://docusaurus.io
- https://www.docz.site
- https://docsify.js.org

Please leave your suggestions below.

**Comment by pardom** [comment]
@kevc @torresmi

**Comment by torresmi** [comment]
I would rank them in the following for this:
1. Docsify
2. Docusaurus
3. Docsify

They all look nice but Docsify seems simple to create and deploy. It also has nice themes. I'd assume that would provide everything needed. 

Docusaurus looks like more work but could be nice if we want search and localization. Docz looks like it's better suited for UI demos.

**Comment by pardom** [comment]
Went with Docsify as it doesn't require any static page generation.
