### ISSUE TITLE
Effect breaks Android Build

### ISSUE THREAD

**Issue by dladukedev** [oolong-kt/oolong#68]
**Describe the bug**
Android application fails to build when "effect" is used

**To Reproduce**
I've made the following repo to demonstrate the issue - [Oolong Test](https://github.com/dladukedev/Oolong-Test)
- "master" fails to build
- "working" builds successfully because the "effect" code in [Store.kt](https://github.com/dladukedev/Oolong-Test/blob/working/app/src/main/java/com/dladukedev/oolongtest/Store.kt) is commented out

**Additional context**
I'm using oolong-jvm because this is just going to run on Android and doesn't require using Kotlin Multi-Platform. I am unsure if that is related because everything else appears to work as expected

**Comment by dladukedev** [comment]
**More context as I have looked into this**

The build seems to take issue with ```suspend CoroutineScope.(dispatch: Dispatch<Msg>)```

So changing ```Effect``` "fixes" the build issue
Broken - ```typealias Effect<Msg> = suspend CoroutineScope.(dispatch: Dispatch<Msg>) -> Any?```
Working - ```typealias Effect<Msg> = suspend CoroutineScope.() -> Any?```

For now, I can use this as a work around
```fun <Msg : Any> effect(msg: suspend CoroutineScope.() -> Msg) = delay(0, msg)```

**Comment by pardom** [comment]
Sorry, didn't see this issue come through. Is this issue still present in `2.0.2-SNAPSHOT`?

**Comment by dladukedev** [comment]
Checked 2.0.2-SNAPSHOT in Studio Canary 7, and got the same issue. From the error message it looks like it's related to the IR, so this issue may fix itself.

**Comment by pardom** [comment]
Yes, I think you're right. I did some exploratory work with Compose recently and ran into some IR issues. I don't have time today to look, but these might lead you to a solution if it's the same issue I was facing.

https://youtrack.jetbrains.com/issue/KT-34583
https://issuetracker.google.com/issues/143232368

**Comment by dladukedev** [comment]
Thanks for closing this.

In case anyone else comes across this issue and the IR issues still haven't been resolved, I've added a branch using multiple modules that gets around the current issues.

https://github.com/dladukedev/Oolong-Test/tree/multi-module
